Updated specs to test for BUNDLE_GEMFILE and GEM_SPECFILE.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -7,7 +7,24 @@ export LANGUAGE=en_US.UTF-8
 export LC_ALL=en_US.UTF-8
 export LANG=en_US.UTF-8
 
-build=$(cd "$1"; pwd); cache=$(cd "$2"; pwd)
+if [ -n "$1" ]; then
+    if [ -d "$1" ]; then
+        build=$(cd "$1"; pwd)
+    else
+        echo "ERROR: Invalid build path, aborting."
+        exit 1
+    fi
+else
+    echo "ERROR: Build path is not specified, aborting."
+    exit 1
+fi
+
+if [ -d "$2" ]; then
+    cache=$(cd "$2"; pwd)
+else
+    cache=""
+fi
+
 bin_dir=$(cd $(dirname $0); pwd)
 buildpack_fpm_dir=$(dirname "$bin_dir")
 
@@ -38,38 +55,17 @@ if [ -f "$build/.env.fury-buildpack-fpm" ]; then
     source "$build/.env.fury-buildpack-fpm"
 fi
 
-# == BEGIN Rubygems specific ==
-if [ -n "$build" ]; then
-    spc_count=$(find "$build" -maxdepth 1 -name '*.gemspec' | wc -l)
-else
-    spc_count=0
-fi
-
-if [ "$spc_count" -gt 1 ]; then
-    echo "ERROR: Multiple .gemspec files present in package root"
-    exit 1
-fi
-
 if [ -n "$BUNDLE_GEMFILE" ]; then
     eval "export BUNDLE_GEMFILE=$BUNDLE_GEMFILE"
 fi
 
-if [ -f "$BUNDLE_GEMFILE" ]; then
-    echo "Using Gemfile    : $BUNDLE_GEMFILE"
-else
-    unset BUNDLE_GEMFILE
+if [ -n "$GEM_SPECFILE" ]; then
+    eval "export GEM_SPECFILE=$GEM_SPECFILE"
 fi
 
-if ls "$build"/*.gemspec &> /dev/null; then
-    gemspec_file=$(basename $(ls "$build"/*.gemspec | head -n 1))
-    echo "Gemspec file     : $gemspec_file"
+if [ -z "$TEST_NOPACKGUY" ]; then
+    cd "$build" && $bin_dir/support/packguy "$build" "$cache"
+    exit ${PIPESTATUS[0]}
 else
-    echo "ERROR: Found no gemspec, compile not supported." && exit 1
+  exit 0
 fi
-
-echo "=================="
-echo ""
-# == END Rubygems specific ==
-
-cd "$build" && $bin_dir/support/packguy "$build" "$cache"
-exit ${PIPESTATUS[0]}
